---

- name: install apt packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - nginx
    - nginx-full

- name: remove default page
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
